server:
  port: 8082
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/fast_food_app
    username: postgres
    password: 2002
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  sql:
    init:
      mode: always
  application:
    name: COURIERMOBILE
  mvc:
    servlet:
      path: /api/courierMobile
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true